name:                complex-hsv
version:             0.1.0.0
github:              xavier2910/complex-hsv
license:             BSD-3-Clause
author:              Xavier Distelzweig
maintainer:          x.distelzweig@gmail.com
copyright:           2024 Xavier Distelzweig

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Graph complex functions using hsv colors
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/xavier2910/complex-hsv#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  complex-hsv-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - complex-hsv
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  complex-hsv-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - complex-hsv
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
